#!/usr/bin/env zsh
set -euo pipefail

# Get current git branch
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
# Sanitize for branch name (replace / with -)
BRANCH_NAME="preview-${GIT_BRANCH//\//-}"

echo "Creating preview environment branches..."
echo "Git branch: $GIT_BRANCH"
echo "Branch name: $BRANCH_NAME"

# Check required environment variables
: "${NEON_PROJECT_ID:?Error: NEON_PROJECT_ID not set}"
: "${NEON_API_KEY:?Error: NEON_API_KEY not set}"
: "${TIGRIS_PROJECT_ID:?Error: TIGRIS_PROJECT_ID not set}"
: "${TIGRIS_API_KEY:?Error: TIGRIS_API_KEY not set}"

# ============================================================================
# Create Neon Database Branch
# ============================================================================

echo ""
echo "Creating Neon database branch..."

NEON_RESPONSE=$(curl -s -X POST \
  "https://console.neon.tech/api/v2/projects/${NEON_PROJECT_ID}/branches" \
  -H "Authorization: Bearer ${NEON_API_KEY}" \
  -H "Content-Type: application/json" \
  -d "{
    \"branch\": {
      \"name\": \"${BRANCH_NAME}\",
      \"parent_id\": \"main\"
    }
  }")

NEON_BRANCH_ID=$(echo "$NEON_RESPONSE" | jq -r '.branch.id')
NEON_ENDPOINT=$(echo "$NEON_RESPONSE" | jq -r '.endpoints[0].host')

if [ "$NEON_ENDPOINT" = "null" ]; then
  echo "Error creating Neon branch:"
  echo "$NEON_RESPONSE" | jq '.'
  exit 1
fi

echo "✓ Neon branch created:"
echo "  Branch ID: $NEON_BRANCH_ID"
echo "  Endpoint:  $NEON_ENDPOINT"

# ============================================================================
# Create Tigris Bucket Branch
# ============================================================================

echo ""
echo "Creating Tigris bucket branch..."

# Tigris branch name format: {parent-bucket}--{branch-name}
TIGRIS_PARENT_BUCKET="zinc-production-files"
TIGRIS_BRANCH_BUCKET="${TIGRIS_PARENT_BUCKET}--${BRANCH_NAME}"

TIGRIS_RESPONSE=$(curl -s -X POST \
  "https://api.preview.tigrisdata.cloud/v1/projects/${TIGRIS_PROJECT_ID}/buckets/${TIGRIS_PARENT_BUCKET}/branches" \
  -H "Authorization: Bearer ${TIGRIS_API_KEY}" \
  -H "Content-Type: application/json" \
  -d "{
    \"name\": \"${BRANCH_NAME}\"
  }")

TIGRIS_STATUS=$(echo "$TIGRIS_RESPONSE" | jq -r '.status')

if [ "$TIGRIS_STATUS" != "created" ]; then
  echo "Error creating Tigris branch:"
  echo "$TIGRIS_RESPONSE" | jq '.'
  exit 1
fi

echo "✓ Tigris branch created:"
echo "  Bucket:   $TIGRIS_BRANCH_BUCKET"
echo "  Endpoint: fly.storage.tigris.dev"

# ============================================================================
# Generate Helm Values Override
# ============================================================================

echo ""
echo "Generating Helm values override..."

cat >./infra/root_chart/values.absol-generated.yaml <<EOF
# Auto-generated by create-branches.sh
# DO NOT COMMIT THIS FILE

maindb:
  enable: true
  type: external

  external:
    host: $NEON_ENDPOINT
    port: 5432
    database: arene-zinc
    sslMode: require

  branch:
    enabled: true
    parentBranch: main
    branchName: $BRANCH_NAME
    branchId: $NEON_BRANCH_ID
    projectId: $NEON_PROJECT_ID

mainstorage:
  enable: true
  type: external

  external:
    endpoint: https://fly.storage.tigris.dev
    region: auto
    bucket: $TIGRIS_BRANCH_BUCKET

  branch:
    enabled: true
    parentBucket: $TIGRIS_PARENT_BUCKET
    branchName: $BRANCH_NAME
    projectId: $TIGRIS_PROJECT_ID

# Use local Dragonfly for cache (no branching needed)
maincache:
  enable: true
  type: crd
  crd:
    replicas: 1
EOF

echo "✓ Values file created: ./infra/root_chart/values.absol-generated.yaml"

# ============================================================================
# Save Branch Info for Cleanup
# ============================================================================

cat >./.preview-branches <<EOF
BRANCH_NAME=$BRANCH_NAME
NEON_BRANCH_ID=$NEON_BRANCH_ID
NEON_ENDPOINT=$NEON_ENDPOINT
TIGRIS_BRANCH_BUCKET=$TIGRIS_BRANCH_BUCKET
NEON_PROJECT_ID=$NEON_PROJECT_ID
TIGRIS_PROJECT_ID=$TIGRIS_PROJECT_ID
EOF

echo ""
echo "✓ Branch info saved to ./.preview-branches"
echo ""
echo "Preview environment branches ready!"
echo "Deploy with: garden deploy --env absol -f ./infra/root_chart/values.absol-generated.yaml"
