version: '3'

tasks:
  create:
    desc: Create k3d cluster (reads landscape from dev.yaml)
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  kubeconfig:
    desc: Regenerate merged kubeconfig from all clusters
    cmds:
      - ./scripts/local/regenerate-kubeconfig.sh
