$schema: ./schema.json
# Native
App:
  Landscape: raichu
  EnableSwagger: true
  GenerateConfig: false
Swagger:
  Title: Raichu Arene Zinc API
# OTEL
Logs:
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: true
Trace:
  Exporter:
    Otlp:
      Enabled: true

Metrics:
  Exporter:
    Otlp:
      Enabled: true

# Infra-based
Database:
  MAIN:
    AutoMigrate: false

Cache:
  MAIN:
    SSL: true
# external
HttpClient: {}
Auth:
  Settings:
    Issuer: # to be filled
    Audience: https://api.zinc.arene.raichu
    Domain: # to be filled
